ScreenManager:
    LoginScreen:
    MainStudent:
    LoggedStudent
    MainProfessor:
    SignProfessor:
    Signed:
    LoggedProfessor:
    MyRooms:
    MainAdmin:
    MyData:
    MySummary:

<LoginScreen>:
    id: ID_loginscreen
    name: 'kv_login'
    labelID_loginscreen: labelID_loginscreen
    MDLabel:
        id: labelID_loginscreen
        text: 'WEBCAM CHEAT DETECTION'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.85}
        font_size: 30
    Image:
        source: 'UI/students.png'
        allow_stretch: True
        size_hint_x: 0.23
        pos_hint: {'center_x': .3, 'center_y': 0.52}
    Image:
        source: 'UI/teacher.png'
        allow_stretch: True
        size_hint_x: 0.29
        pos_hint: {'center_x': .7, 'center_y': 0.55}
    MagicButton1:
        text: 'Im a STUDENT'
        pos_hint: {'center_x': .3, 'center_y': 0.30}
        on_release: 
            self.grow() 
            root.manager.current = 'kv_MainStudent'
            root.manager.transition.direction = "up"
    MagicButton1:
        text: 'Im a PROFESSOR'
        pos_hint: {'center_x': .71, 'center_y': 0.30}
        on_release: 
            self.grow()
            root.manager.current = 'kv_MainProf'
            root.manager.transition.direction = "up"


<MainStudent>:
    id: ID_MainStudentScreen
    name: 'kv_MainStudent'
    labelID_studentlabel: labelID_studentlabel
    textID_studentname:  textID_studentname
    textID_roomname: textID_roomname
    textID_inputprofmail: textID_inputprofmail
    Image:
        source: 'UI/face-recog.png'
        allow_stretch: True
        size_hint_x: 0.23
        pos_hint: {'center_x': .2, 'center_y': 0.52}
    MDLabel:
        id: labelID_studentlabel
        text: 'STUDENTS PAGE'
        halign: 'center'
        pos_hint: {'center_x': 0.55, 'center_y': 0.87}
        font_size: 28
    MDTextField:
        id: textID_studentname
        hint_text: 'STUDENT IDENTIFICATION'
        halign: 'center'
        pos_hint: {'center_x': 0.58, 'center_y': 0.3}
        size_hint: .4, 1
    MDTextField:
        id: textID_inputprofmail
        hint_text: 'PROFESSORS EMAIL'
        halign: 'center'
        pos_hint: {'center_x': 0.58, 'center_y': 0.17}
        size_hint: .4, 1
    MDTextField:
        id: textID_roomname
        hint_text: 'ROOM NAME'
        halign: 'center'
        pos_hint: {'center_x': 0.58, 'center_y': 0.03}
        size_hint: .4, 1
    MagicButton1:
        text: 'JOIN ROOM'
        pos_hint: {'center_x': .70, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.joinRoom()
    MagicButton1:
        text: 'HOME'
        pos_hint: {'center_x': .50, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.manager.current = 'kv_login'
            root.manager.transition.direction = "up"


<LoggedStudent>:
    id: ID_LoggedStudentScreen
    name: 'kv_LoggedStudent'
    labelID_loggedstudentlabel: labelID_loggedstudentlabel
    MDLabel:
        id: labelID_loggedstudentlabel
        text: 'Logged Student Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        font_size: 28
    MagicButton1:
        text: 'Start Exam'
        pos_hint: {'center_x': .6, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.createStudentLog()
    MagicButton1:
        text: 'LOGOUT'
        pos_hint: {'center_x': .4, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.manager.current = 'kv_MainStudent'
            root.manager.transition.direction = "up"


<MainProfessor>:
    id: ID_MainProfScreen
    name: 'kv_MainProf'
    labelID_mainprof: labelID_mainprof
    textID_profmail:  textID_profmail
    textID_profpass: textID_profpass
    Image:
        source: 'UI/Database.png'
        allow_stretch: True
        size_hint_x: 0.29
        pos_hint: {'center_x': .75, 'center_y': 0.55}
    MDLabel:
        id: labelID_mainprof
        text: 'LOGIN PAGE'
        halign: 'center'
        pos_hint: {'center_x': 0.3, 'center_y': 0.85}
        font_size: 28
    MDTextField:
        id: textID_profmail
        hint_text: 'EMAIL'
        halign: 'center'
        pos_hint: {'center_x': 0.3, 'center_y': 0.25}
        size_hint: .4, 1
    MDTextField:
        id: textID_profpass
        hint_text: 'PASSWORD'
        halign: 'center'
        pos_hint: {'center_x': 0.3, 'center_y': 0.1}
        size_hint: .4, 1
    MagicButton1:
        text: 'LOGIN'
        pos_hint: {'center_x': .38, 'center_y': 0.3}
        on_release: 
            self.grow()
            root.logIn()
    MagicButton1:
        text: 'HOME'
        pos_hint: {'center_x': .23, 'center_y': 0.3}
        on_release: 
            self.grow()
            root.resetText()
            root.manager.current = 'kv_login'
            root.manager.transition.direction = "up"
    MagicButton1:
        text: 'CREATE ACCOUNT'
        pos_hint: {'center_x': .3, 'center_y': 0.15}
        on_release: 
            self.grow()
            root.manager.current = 'kv_SignProf'
            root.manager.transition.direction = "up"


<LoggedProfessor>:
    id: ID_LoggedProfScreen
    name: 'kv_LoggedProf'
    labelID_loggedprof: labelID_loggedprof
    textID_createroom: textID_createroom
    MDLabel:
        id: labelID_loggedprof
        text: 'Logged Professor Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.78}
        font_size: 28
    MDTextField:
        id: textID_createroom
        hint_text: 'ENTER ROOM NAME'
        halign: 'center'
        pos_hint: {'center_x': 0.65, 'center_y': 0.1}
        size_hint: .4, 1
    MagicButton1:
        text: 'CREATE ROOM'
        pos_hint: {'center_x': .33, 'center_y': 0.5}
        on_release: 
            self.grow()
            root.createRoom()
    MagicButton1:
        text: 'MY ROOMS'
        pos_hint: {'center_x': .59, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.loadRooms()
            root.manager.current = 'kv_MyRooms'
    MagicButton1:
        text: 'LOGOUT'
        pos_hint: {'center_x': .42, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.manager.current = 'kv_MainProf'
            root.manager.transition.direction = "up"


<MyRooms>:
    name: 'kv_MyRooms'
    listID_MainList: listID_MainList
    buttonID_Lenient: buttonID_Lenient
    buttonID_Moderate: buttonID_Moderate
    buttonID_Strict: buttonID_Strict
    buttonID_CreateSummary: buttonID_CreateSummary
    ScrollView:
        size_hint: 0.8, 0.5
        pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        MDList:
            id: listID_MainList
    MagicButton1:
        text: 'BACK'
        pos_hint: {'center_x': .2, 'center_y': 0.05}
        on_release: 
            self.grow()
            root.clearList()
            root.manager.current = 'kv_LoggedProf'
            root.manager.transition.direction = "up"
    MagicButton1:
        id: buttonID_CreateSummary
        text: 'CREATE SUMMARY'
        pos_hint: {'center_x': .2, 'center_y': 0.2}
        disabled: True
        on_release: 
            self.grow()
            root.createSummary()
            root.manager.current = 'kv_MySummary'
            root.manager.transition.direction = "up"
    MagicButton1:
        id: buttonID_Lenient
        text: 'LENIENT'
        pos_hint: {'center_x': .7, 'center_y': 0.05}
        opacity: .5
        on_release: 
            self.grow()
            root.setLenient()
    MagicButton1:
        id: buttonID_Moderate
        text: 'MODERATE'
        opacity: 1
        pos_hint: {'center_x': .7, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.setModerate()
    MagicButton1:
        id: buttonID_Strict
        text: 'STRICT'
        opacity: .5
        pos_hint: {'center_x': .7, 'center_y': 0.4}
        on_release: 
            self.grow()
            root.setStrict()


<MySummary>:
    name: 'kv_MySummary'
    MDLabel:
        text: 'SUMMARY HAS BEEN CREATED\nPLEASE CHECK RESULTS FOLDER'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        font_size: 28
    MagicButton1:
        text: 'OK'
        pos_hint: {'center_x': .5, 'center_y': 0.25}
        on_release: 
            self.grow()
            root.manager.current = 'kv_MyRooms'
            root.manager.transition.direction = "up"



<MyData>:
    name: 'kv_MyData'
    listID_DataList: listID_DataList
    imageID_DataImage: imageID_DataImage
    labelID_DataLabel: labelID_DataLabel
    Image:
        id: imageID_DataImage
        pos_hint: {'center_x': 0.2, 'center_y': 0.75}
        size_hint: 0.3, 0.3
        source: "UI/default.jpg"
    MDLabel:
        id: labelID_DataLabel
        text: 'STATUS'
        halign: 'center'
        pos_hint: {'center_x': 0.2, 'center_y': 0.45}
        font_size: 13
    ScrollView:
        size_hint: 0.55, 0.5
        pos_hint: {'center_x': 0.65, 'center_y': 0.7}
        MDList:
            id: listID_DataList
    MagicButton1:
        text: 'SHOW GRAPH'
        pos_hint: {'center_x': .5, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.showGraph()
    MagicButton1:
        text: 'BACK'
        pos_hint: {'center_x': .2, 'center_y': 0.2}
        on_release: 
            self.grow()
            root.clearList()
            root.manager.current = 'kv_MyRooms'
            root.manager.transition.direction = "up"


<SignProfessor>:
    id: ID_SignProfScreen
    name: 'kv_SignProf'
    labelID_signprof: labelID_signprof
    textID_signprofmail:  textID_signprofmail
    textID_signprofpass: textID_signprofpass
    MDLabel:
        id: labelID_signprof
        text: 'Please enter your email and password'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        font_size: 28
    MDTextField:
        id: textID_signprofmail
        hint_text: 'NEW EMAIL'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.3}
        size_hint: .4, 1
    MDTextField:
        id: textID_signprofpass
        hint_text: 'NEW PASSWORD'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.1}
        size_hint: .4, 1
    MagicButton1:
        text: 'SIGN UP'
        pos_hint: {'center_x': .6, 'center_y': 0.25}
        on_release: 
            self.grow()
            root.signUpProcess()
            root.manager.current = 'kv_Signed'
            root.manager.transition.direction = "up"
    MagicButton1:
        text: 'BACK'
        pos_hint: {'center_x': .4, 'center_y': 0.25}
        on_release: 
            self.grow()
            root.manager.current = 'kv_MainProf'
            root.manager.transition.direction = "up"


<Signed>:
    id: ID_SignedScreen
    name: 'kv_Signed'
    labelID_signed: labelID_signed
    MDLabel:
        id: labelID_signed
        text: 'ACCOUNT HAS BEEN CREATED'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        font_size: 28
    MagicButton1:
        text: 'OK'
        pos_hint: {'center_x': .5, 'center_y': 0.25}
        on_release: 
            self.grow()
            root.manager.current = 'kv_MainProf'
            root.manager.transition.direction = "up"


<MainAdmin>:
    id: ID_MainAdminScreen
    name: 'kv_MainAdmin'
    labelID_adminlabel: labelID_adminlabel
    MDLabel:
        id: labelID_adminlabel
        text: 'ADMIN Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        font_size: 
    
    MagicButton1:
        text: 'HOME'
        on_release: 
            self.grow()
            root.manager.current = 'kv_login'
            root.manager.transition.direction = "up"